(() => {
  'use strict';
  const series={
    S:{code:'VZ-S',count:18,imageDir:'assets/products/s-series',imageSkus:true,names:['Classic Shirt Hanger','Slim Shirt Hanger','Broad-Shoulder Shirt Hanger','Anti-Slip Shirt Hanger','Blouse Hanger','Knitwear Hanger','Lightweight Jacket Hanger','Tailored Jacket Hanger','Classic Suit Hanger','Wide-Shoulder Suit Hanger','Suit Hanger with Trouser Bar','Jacket Hanger with Trouser Bar','Heavy Jacket Hanger','Coat Hanger','Overcoat Hanger','Garment Presentation Hanger','Compact Retail Hanger','Signature Shoulder Hanger'],benefits:['Clean shoulder line for polished shirt presentation.','Slim profile designed for efficient premium wardrobe spacing.','Broader shoulder support for a more structured silhouette.','Enhanced surface control to help garments stay neatly positioned.','Refined proportions suited to lightweight blouses and tops.','Gentle shoulder geometry for knitwear-focused garment care.','Balanced form for lightweight jackets and layered presentation.','Tailoring-inspired shoulder support for sharper jacket display.','Classic suit proportions for coordinated formalwear presentation.','Expanded shoulder profile for structured suit presentation.','Integrated trouser bar supports coordinated suit merchandising.','Jacket-and-trouser format for efficient complete-look presentation.','Substantial shoulder form suited to heavier jacket presentation.','Fuller profile designed for coat support and premium display.','Extended support concept for long and heavier outerwear.','Presentation-led silhouette for premium retail and showroom use.','Space-conscious format for high-density retail presentation.','Distinctive shoulder geometry for signature brand presentation.']},
    T:{code:'VZ-T',count:14,imageSkus:false,names:['Straight Trouser Bar Hanger','Non-Slip Trouser Bar Hanger','Clamp-Bar Trouser Hanger','Open-Bar Trouser Hanger','Double-Bar Trouser Hanger','Classic Two-Clip Trouser Hanger','Adjustable Two-Clip Trouser Hanger','Wide-Grip Trouser Hanger','Classic Skirt Hanger','Adjustable Skirt Hanger','Delicate-Fabric Clip Hanger','Heavy-Duty Bottom Hanger','Compact Bottom Hanger','Coordinated Suit-Bottom Hanger']},
    P:{code:'VZ-P',count:16,imageSkus:false,names:['Luxury Wood Hanger','Premium Lacquer Hanger','Fabric-Covered Hanger','Velvet-Finish Hanger','Acrylic Display Hanger','Bridal & Gown Hanger','Lingerie & Delicates Hanger','Scarf & Accessory Hanger','Luxury Boutique Display Hanger','Anti-Theft Hotel Hanger','Hotel Open-Hook Hanger','Hotel Closed-Ring Hanger','Robe & Spa Hanger','Uniform & Professional Hanger','Sustainable-Material Hanger','Bespoke Signature Hanger']},
    K:{code:'VZ-K',count:10,imageDir:'assets/products/k-series',imageSkus:true,names:['Baby Garment Hanger','Kids Classic Hanger','Kids Shirt & Top Hanger','Kids Trouser & Skirt Hanger','Kids Two-Clip Hanger','Junior Jacket Hanger','Kids Shirt & Top Hanger — Premium Wood','Kids Dress Hanger','Kids Sweater & Knit Hanger','Kids Multi-Function Hanger'],benefits:['Small-scale rounded wood form designed for babywear presentation.','Classic children’s proportions for versatile everyday garment presentation.','Slimmer wood profile suited to shirts, T-shirts and lightweight tops.','Wooden crossbar with adjustable clips for trousers, skirts and coordinated bottoms.','Sculpted wooden body with two adjustable protected clips for refined garment care.','Broader shoulder support for junior jackets, suits and outerwear.','Premium natural-wood form with ergonomic shoulders and strap notches.','Dress-focused wooden form with strap notches for occasionwear presentation.','Wider rounded shoulders designed to support sweaters, knitwear and delicate tops.','Multi-purpose wood construction with shoulder notches and anti-slip shoulder control.']}
  };
  const order=['S','T','P','K'];
  const sku=(key,index)=>`VZ-${key}${String(index+1).padStart(3,'0')}`;
  const image=(key,index)=>series[key].imageSkus?`${series[key].imageDir}/${sku(key,index)}.png`:null;
  window.VAYRENZA_PRODUCTS=Object.freeze({version:'3.0',total:58,order,series,sku,image});
})();