(() => {
  'use strict';
  const names={
    en:{
      S:['Classic Shirt Hanger','Slim Shirt Hanger','Broad-Shoulder Shirt Hanger','Anti-Slip Shirt Hanger','Blouse Hanger','Knitwear Hanger','Lightweight Jacket Hanger','Tailored Jacket Hanger','Classic Suit Hanger','Wide-Shoulder Suit Hanger','Suit Hanger with Trouser Bar','Jacket Hanger with Trouser Bar','Heavy Jacket Hanger','Coat Hanger','Overcoat Hanger','Garment Presentation Hanger','Compact Retail Hanger','Signature Shoulder Hanger'],
      T:['Straight Trouser Bar Hanger','Non-Slip Trouser Bar Hanger','Clamp-Bar Trouser Hanger','Open-Bar Trouser Hanger','Double-Bar Trouser Hanger','Classic Two-Clip Trouser Hanger','Adjustable Two-Clip Trouser Hanger','Wide-Grip Trouser Hanger','Classic Skirt Hanger','Adjustable Skirt Hanger','Delicate-Fabric Clip Hanger','Heavy-Duty Bottom Hanger','Compact Bottom Hanger','Coordinated Suit-Bottom Hanger'],
      P:['Luxury Wood Hanger','Premium Lacquer Hanger','Fabric-Covered Hanger','Velvet-Finish Hanger','Acrylic Display Hanger','Bridal & Gown Hanger','Lingerie & Delicates Hanger','Scarf & Accessory Hanger','Luxury Boutique Display Hanger','Anti-Theft Hotel Hanger','Hotel Open-Hook Hanger','Hotel Closed-Ring Hanger','Robe & Spa Hanger','Uniform & Professional Hanger','Sustainable-Material Hanger','Bespoke Signature Hanger'],
      K:['Baby Garment Hanger','Kids Classic Hanger','Kids Shirt & Top Hanger','Kids Trouser & Skirt Hanger','Kids Two-Clip Hanger','Junior Jacket Hanger','Kids Shirt & Top Hanger — Premium Wood','Kids Dress Hanger','Kids Sweater & Knit Hanger','Kids Multi-Function Hanger']
    },
    es:{
      S:['Percha clásica para camisa','Percha fina para camisa','Percha para camisa de hombro ancho','Percha antideslizante para camisa','Percha para blusa','Percha para prendas de punto','Percha para chaqueta ligera','Percha para chaqueta de sastrería','Percha clásica para traje','Percha para traje de hombro ancho','Percha para traje con barra de pantalón','Percha para chaqueta con barra de pantalón','Percha para chaqueta pesada','Percha para abrigo','Percha para abrigo largo','Percha de presentación de prendas','Percha compacta para retail','Percha de hombro Signature'],
      T:['Percha de pantalón con barra recta','Percha de pantalón con barra antideslizante','Percha de pantalón con barra de presión','Percha de pantalón con barra abierta','Percha de pantalón con doble barra','Percha clásica de pantalón con dos pinzas','Percha ajustable de pantalón con dos pinzas','Percha de pantalón de agarre ancho','Percha clásica para falda','Percha ajustable para falda','Percha con pinzas para tejidos delicados','Percha reforzada para prendas inferiores','Percha compacta para prendas inferiores','Percha coordinada para pantalón de traje'],
      P:['Percha de madera de lujo','Percha lacada premium','Percha revestida de tela','Percha con acabado aterciopelado','Percha expositora de acrílico','Percha para novia y vestido','Percha para lencería y prendas delicadas','Percha para bufandas y accesorios','Percha de exposición para boutique de lujo','Percha antirrobo para hotel','Percha de hotel con gancho abierto','Percha de hotel con anillo cerrado','Percha para albornoz y spa','Percha para uniforme profesional','Percha de material sostenible','Percha Signature a medida'],
      K:['Percha para prendas de bebé','Percha clásica infantil','Percha infantil para camisa y top','Percha infantil para pantalón y falda','Percha infantil de dos pinzas','Percha para chaqueta juvenil','Percha infantil para camisa y top — madera premium','Percha infantil para vestido','Percha infantil para suéter y punto','Percha infantil multifunción']
    },
    fr:{
      S:['Cintre chemise classique','Cintre chemise fin','Cintre chemise épaules larges','Cintre chemise antidérapant','Cintre chemisier','Cintre maille','Cintre veste légère','Cintre veste tailleur','Cintre costume classique','Cintre costume épaules larges','Cintre costume avec barre pantalon','Cintre veste avec barre pantalon','Cintre veste lourde','Cintre manteau','Cintre pardessus','Cintre de présentation','Cintre retail compact','Cintre épaule Signature'],
      T:['Cintre pantalon à barre droite','Cintre pantalon à barre antidérapante','Cintre pantalon à barre de serrage','Cintre pantalon à barre ouverte','Cintre pantalon à double barre','Cintre pantalon classique à deux pinces','Cintre pantalon réglable à deux pinces','Cintre pantalon à prise large','Cintre jupe classique','Cintre jupe réglable','Cintre à pinces pour tissus délicats','Cintre renforcé pour bas','Cintre compact pour bas','Cintre coordonné pour bas de costume'],
      P:['Cintre bois luxe','Cintre laqué premium','Cintre recouvert de tissu','Cintre finition velours','Cintre de présentation acrylique','Cintre mariée et robe','Cintre lingerie et délicats','Cintre écharpes et accessoires','Cintre de présentation boutique de luxe','Cintre hôtel antivol','Cintre hôtel à crochet ouvert','Cintre hôtel à anneau fermé','Cintre peignoir et spa','Cintre uniforme professionnel','Cintre en matériau durable','Cintre Signature sur mesure'],
      K:['Cintre pour vêtements de bébé','Cintre enfant classique','Cintre enfant chemise et haut','Cintre enfant pantalon et jupe','Cintre enfant à deux pinces','Cintre veste junior','Cintre enfant chemise et haut — bois premium','Cintre enfant pour robe','Cintre enfant pull et maille','Cintre enfant multifonction']
    },
    de:{
      S:['Klassischer Hemdenbügel','Schmaler Hemdenbügel','Hemdenbügel mit breiter Schulter','Rutschfester Hemdenbügel','Blusenbügel','Strickwarenbügel','Bügel für leichte Jacken','Bügel für Sakko','Klassischer Anzugbügel','Anzugbügel mit breiter Schulter','Anzugbügel mit Hosensteg','Jackenbügel mit Hosensteg','Bügel für schwere Jacken','Mantelbügel','Bügel für lange Mäntel','Präsentationsbügel','Kompakter Retail-Bügel','Signature-Schulterbügel'],
      T:['Hosenbügel mit geradem Steg','Rutschfester Hosenbügel','Hosenbügel mit Klemmsteg','Hosenbügel mit offenem Steg','Hosenbügel mit Doppelsteg','Klassischer Hosenbügel mit zwei Clips','Verstellbarer Hosenbügel mit zwei Clips','Hosenbügel mit breitem Griff','Klassischer Rockbügel','Verstellbarer Rockbügel','Clipbügel für empfindliche Stoffe','Robuster Unterteilbügel','Kompakter Unterteilbügel','Abgestimmter Anzug-Unterteilbügel'],
      P:['Luxus-Holzbügel','Premium-Lackbügel','Stoffbezogener Bügel','Bügel mit Samtfinish','Acryl-Präsentationsbügel','Braut- und Abendkleiderbügel','Bügel für Dessous und Feines','Schal- und Accessoirebügel','Luxus-Boutique-Präsentationsbügel','Diebstahlsicherer Hotelbügel','Hotelbügel mit offenem Haken','Hotelbügel mit geschlossenem Ring','Bademantel- und Spa-Bügel','Uniform- und Berufskleiderbügel','Bügel aus nachhaltigem Material','Maßgefertigter Signature-Bügel'],
      K:['Baby-Kleiderbügel','Klassischer Kinderbügel','Kinderbügel für Hemd & Oberteil','Kinderbügel für Hose & Rock','Kinderbügel mit zwei Clips','Junior-Jackenbügel','Kinderbügel für Hemd & Oberteil — Premiumholz','Kinder-Kleiderbügel','Kinderbügel für Pullover & Strick','Multifunktionaler Kinderbügel']
    },
    'zh-CN':{
      S:['经典衬衫衣架','纤薄衬衫衣架','宽肩衬衫衣架','防滑衬衫衣架','女式上衣衣架','针织衫衣架','轻型夹克衣架','精裁夹克衣架','经典西装衣架','宽肩西装衣架','带裤杆西装衣架','带裤杆夹克衣架','重型夹克衣架','大衣衣架','长大衣衣架','服装陈列衣架','紧凑型零售衣架','标志性肩型衣架'],
      T:['直杆裤架','防滑裤杆衣架','夹杆式裤架','开放式裤杆衣架','双杆裤架','经典双夹裤架','可调双夹裤架','宽夹持裤架','经典半裙衣架','可调半裙衣架','精细面料夹式衣架','重型下装衣架','紧凑型下装衣架','西装配套下装衣架'],
      P:['奢华木质衣架','高端烤漆衣架','包布衣架','植绒饰面衣架','亚克力陈列衣架','婚纱与礼服衣架','内衣与精细服饰衣架','围巾与配饰衣架','奢华精品店陈列衣架','酒店防盗衣架','酒店开放式挂钩衣架','酒店闭环式衣架','浴袍与水疗衣架','制服与专业衣架','可持续材料衣架','高端专属定制衣架'],
      K:['婴幼儿衣架','儿童经典衣架','儿童衬衫与上衣衣架','儿童裤装与半裙衣架','儿童艺术木质双夹衣架','青少年夹克衣架','儿童高端木质上装衣架','儿童连衣裙衣架','儿童毛衣与针织衣架','儿童多功能衣架']
    },
    ja:{
      S:['クラシックシャツハンガー','スリムシャツハンガー','ワイドショルダーシャツハンガー','滑り止めシャツハンガー','ブラウスハンガー','ニットウェアハンガー','ライトジャケットハンガー','テーラードジャケットハンガー','クラシックスーツハンガー','ワイドショルダースーツハンガー','トラウザーバー付きスーツハンガー','トラウザーバー付きジャケットハンガー','ヘビージャケットハンガー','コートハンガー','オーバーコートハンガー','ガーメントディスプレイハンガー','コンパクトリテールハンガー','シグネチャーショルダーハンガー'],
      T:['ストレートトラウザーバーハンガー','滑り止めトラウザーバーハンガー','クランプバートラウザーバーハンガー','オープンバートラウザーバーハンガー','ダブルバートラウザーハンガー','クラシック2クリップトラウザーハンガー','調整式2クリップトラウザーハンガー','ワイドグリップトラウザーハンガー','クラシックスカートハンガー','調整式スカートハンガー','デリケート素材用クリップハンガー','ヘビーデューティーボトムハンガー','コンパクトボトムハンガー','スーツボトムコーディネートハンガー'],
      P:['ラグジュアリーウッドハンガー','プレミアムラッカーハンガー','ファブリックカバーハンガー','ベルベット仕上げハンガー','アクリルディスプレイハンガー','ブライダル＆ガウンハンガー','ランジェリー＆デリケートハンガー','スカーフ＆アクセサリーハンガー','ラグジュアリーブティックディスプレイハンガー','ホテル用盗難防止ハンガー','ホテル用オープンフックハンガー','ホテル用クローズドリングハンガー','ローブ＆スパハンガー','ユニフォーム＆プロフェッショナルハンガー','サステナブル素材ハンガー','ビスポーク・シグネチャーハンガー'],
      K:['ベビーガーメントハンガー','キッズクラシックハンガー','キッズシャツ＆トップハンガー','キッズパンツ＆スカートハンガー','キッズ2クリップハンガー','ジュニアジャケットハンガー','キッズシャツ＆トップハンガー — プレミアムウッド','キッズドレスハンガー','キッズセーター＆ニットハンガー','キッズ多機能ハンガー']
    },
    ko:{
      S:['클래식 셔츠 행거','슬림 셔츠 행거','와이드 숄더 셔츠 행거','논슬립 셔츠 행거','블라우스 행거','니트웨어 행거','라이트 재킷 행거','테일러드 재킷 행거','클래식 수트 행거','와이드 숄더 수트 행거','트라우저 바 수트 행거','트라우저 바 재킷 행거','헤비 재킷 행거','코트 행거','오버코트 행거','의류 디스플레이 행거','컴팩트 리테일 행거','시그니처 숄더 행거'],
      T:['스트레이트 트라우저 바 행거','논슬립 트라우저 바 행거','클램프 바 트라우저 행거','오픈 바 트라우저 행거','더블 바 트라우저 행거','클래식 투클립 트라우저 행거','조절식 투클립 트라우저 행거','와이드 그립 트라우저 행거','클래식 스커트 행거','조절식 스커트 행거','섬세한 원단용 클립 행거','헤비듀티 하의 행거','컴팩트 하의 행거','수트 하의 코디네이트 행거'],
      P:['럭셔리 우드 행거','프리미엄 래커 행거','패브릭 커버 행거','벨벳 마감 행거','아크릴 디스플레이 행거','브라이덜 & 가운 행거','란제리 & 델리케이트 행거','스카프 & 액세서리 행거','럭셔리 부티크 디스플레이 행거','호텔 도난방지 행거','호텔 오픈훅 행거','호텔 클로즈드링 행거','로브 & 스파 행거','유니폼 & 프로페셔널 행거','지속가능 소재 행거','비스포크 시그니처 행거'],
      K:['베이비 가먼트 행거','키즈 클래식 행거','키즈 셔츠 & 탑 행거','키즈 팬츠 & 스커트 행거','키즈 투클립 행거','주니어 재킷 행거','키즈 셔츠 & 탑 행거 — 프리미엄 우드','키즈 드레스 행거','키즈 스웨터 & 니트 행거','키즈 멀티펑션 행거']
    }
  };

  const copy={
    en:{status:'2026 CORE COLLECTION',nav:['PRODUCTS','SOLUTIONS','CUSTOM / OEM','SUSTAINABILITY','ABOUT','INSIGHTS','CONTACT'],eyebrow:'2026 CORE COLLECTION',headline:'58 SKUs.<br>One coherent system.',intro:'58 purpose-built hanger solutions across four clear families — helping brands protect garments, strengthen presentation and simplify sourcing across different applications.',total:'Total SKUs',summary:['VZ-S · Suit & Shirt','VZ-T · Trouser & Skirt','VZ-P · Premium & Specialty','VZ-K · Kids & Junior'],series:['Suit & Shirt','Trouser & Skirt','Premium & Specialty','Kids & Junior'],desc:['Preserve shoulder shape and create a consistent premium presentation across shirts, knitwear, jackets, tailoring and coats.','Secure trousers and skirts with dependable grip while supporting garment care and space-efficient presentation.','Specialized solutions for hotels, luxury retail and custom programs where presentation, durability and brand identity matter.','Gentle, proportioned solutions that protect smaller garments and keep baby, kids and junior collections organized and presentation-ready.'],state:'Designed for professional presentation',view:'View full visual',rule:'BUYER GUIDE',ruleTitle:'Clear choices. Confident sourcing.',ruleBody:'Choose by garment type and application, then work with VAYRENZA to confirm the dimensions, materials, finishes, branding and packaging required for your program.',search:'SEARCH',quote:'REQUEST A QUOTE',searchTitle:'PRODUCT SEARCH',placeholder:'Search products by SKU or name',close:'CLOSE',empty:'No matching products',results:n=>`${n} RESULT${n===1?'':'S'}`},
    es:{status:'COLECCIÓN PRINCIPAL 2026',nav:['PRODUCTOS','SOLUCIONES','CUSTOM / OEM','SOSTENIBILIDAD','NOSOTROS','INSIGHTS','CONTACTO'],eyebrow:'COLECCIÓN PRINCIPAL 2026',headline:'58 SKUs.<br>Un sistema coherente.',intro:'58 soluciones de perchas para usos específicos, organizadas en cuatro familias claras para proteger las prendas, reforzar su presentación y simplificar el abastecimiento.',total:'SKUs totales',summary:['VZ-S · Traje y camisa','VZ-T · Pantalón y falda','VZ-P · Premium y especialidad','VZ-K · Infantil y juvenil'],series:['Traje y camisa','Pantalón y falda','Premium y especialidad','Infantil y juvenil'],desc:['Conserve la forma de los hombros y logre una presentación premium uniforme en camisas, punto, chaquetas, sastrería y abrigos.','Sujete pantalones y faldas con fiabilidad, cuidando la prenda y optimizando el espacio de presentación.','Soluciones especializadas para hoteles, retail de lujo y programas personalizados donde importan presentación, durabilidad e identidad de marca.','Soluciones proporcionadas y cuidadosas que protegen prendas pequeñas y mantienen las colecciones de bebé, infantil y juvenil listas para presentar.'],state:'Diseñado para presentación profesional',view:'Ver visual completo',rule:'GUÍA DEL COMPRADOR',ruleTitle:'Opciones claras. Abastecimiento con confianza.',ruleBody:'Seleccione por tipo de prenda y aplicación; después, VAYRENZA le ayuda a confirmar dimensiones, materiales, acabados, branding y embalaje para su programa.',search:'BUSCAR',quote:'SOLICITAR COTIZACIÓN',searchTitle:'BUSCAR EN PRODUCTOS',placeholder:'Buscar por SKU o nombre',close:'CERRAR',empty:'No hay productos coincidentes',results:n=>`${n} RESULTADO${n===1?'':'S'}`},
    fr:{status:'COLLECTION PRINCIPALE 2026',nav:['PRODUITS','SOLUTIONS','CUSTOM / OEM','DURABILITÉ','À PROPOS','INSIGHTS','CONTACT'],eyebrow:'COLLECTION PRINCIPALE 2026',headline:'58 SKUs.<br>Un système cohérent.',intro:'58 solutions de cintres dédiées, organisées en quatre familles claires pour protéger les vêtements, renforcer leur présentation et simplifier l’approvisionnement.',total:'SKUs au total',summary:['VZ-S · Costume et chemise','VZ-T · Pantalon et jupe','VZ-P · Premium et spécialité','VZ-K · Enfant & junior'],series:['Costume et chemise','Pantalon et jupe','Premium et spécialité','Enfant & junior'],desc:['Préservez la ligne d’épaule et créez une présentation premium cohérente pour chemises, mailles, vestes, tailleurs et manteaux.','Maintenez pantalons et jupes avec fiabilité tout en protégeant les vêtements et en optimisant l’espace de présentation.','Des solutions spécialisées pour l’hôtellerie, le retail de luxe et les programmes personnalisés où présentation, durabilité et identité de marque comptent.','Des solutions adaptées qui protègent les petites tailles et gardent les collections bébé, enfant et junior organisées et prêtes à présenter.'],state:'Conçu pour la présentation professionnelle',view:'Voir le visuel complet',rule:'GUIDE ACHETEUR',ruleTitle:'Des choix clairs. Un sourcing maîtrisé.',ruleBody:'Choisissez selon le type de vêtement et l’usage, puis confirmez avec VAYRENZA les dimensions, matériaux, finitions, éléments de marque et emballages nécessaires.',search:'RECHERCHER',quote:'DEMANDER UN DEVIS',searchTitle:'RECHERCHE PRODUITS',placeholder:'Rechercher par SKU ou nom',close:'FERMER',empty:'Aucun produit correspondant',results:n=>`${n} RÉSULTAT${n===1?'':'S'}`},
    de:{status:'KERNKOLLEKTION 2026',nav:['PRODUKTE','LÖSUNGEN','CUSTOM / OEM','NACHHALTIGKEIT','ÜBER UNS','INSIGHTS','KONTAKT'],eyebrow:'KERNKOLLEKTION 2026',headline:'58 SKUs.<br>Ein kohärentes System.',intro:'58 zweckorientierte Bügellösungen in vier klaren Familien — für besseren Kleidungsschutz, stärkere Präsentation und einfachere Beschaffung.',total:'SKUs gesamt',summary:['VZ-S · Anzug & Hemd','VZ-T · Hose & Rock','VZ-P · Premium & Spezial','VZ-K · Kinder & Junior'],series:['Anzug & Hemd','Hose & Rock','Premium & Spezial','Kinder & Junior'],desc:['Bewahren Sie die Schulterform und schaffen Sie eine konsistent hochwertige Präsentation für Hemden, Strick, Jacken, Tailoring und Mäntel.','Sicherer Halt für Hosen und Röcke bei guter Kleiderschonung und platzsparender Präsentation.','Spezialisierte Lösungen für Hotels, Luxus-Retail und individuelle Programme, bei denen Präsentation, Langlebigkeit und Markenidentität zählen.','Schonende, proportional abgestimmte Lösungen für Baby-, Kinder- und Juniorbekleidung, geordnet und präsentationsbereit.'],state:'Für professionelle Präsentation entwickelt',view:'Gesamtansicht öffnen',rule:'EINKÄUFER-GUIDE',ruleTitle:'Klare Auswahl. Sicherere Beschaffung.',ruleBody:'Wählen Sie nach Kleidungsart und Anwendung; anschließend bestätigt VAYRENZA mit Ihnen Maße, Materialien, Oberflächen, Branding und Verpackung für Ihr Programm.',search:'SUCHE',quote:'ANGEBOT ANFRAGEN',searchTitle:'PRODUKTSUCHE',placeholder:'Nach SKU oder Produktname suchen',close:'SCHLIESSEN',empty:'Keine passenden Produkte',results:n=>`${n} TREFFER`},
    'zh-CN':{status:'2026 核心系列',nav:['产品','解决方案','定制 / OEM','可持续发展','关于我们','洞察','联系我们'],eyebrow:'2026 核心系列',headline:'58 个 SKU。<br>一个完整体系。',intro:'58 款针对不同应用而设计的衣架解决方案，归纳为四大清晰系列，帮助品牌保护服装、提升陈列品质，并简化不同场景下的采购与选型。',total:'SKU 总数',summary:['VZ-S · 西装与衬衫','VZ-T · 长裤与半裙','VZ-P · 高端与专业系列','VZ-K · 儿童与青少年'],series:['西装与衬衫','长裤与半裙','高端与专业系列','儿童与青少年'],desc:['帮助保持服装肩部轮廓，为衬衫、针织衫、夹克、西装及大衣建立统一的高品质陈列。','为长裤与半裙提供可靠夹持，同时兼顾服装保护与节省空间的陈列需求。','面向酒店、奢华零售及定制项目的专业解决方案，兼顾陈列品质、耐用性与品牌识别。','以适合儿童服装的比例和柔和结构保护较小尺码服装，让婴幼儿、儿童及青少年系列保持整齐并随时适合陈列。'],state:'为专业服装陈列而设计',view:'查看完整视觉',rule:'采购指南',ruleTitle:'清晰选型，更安心采购。',ruleBody:'您可以先按服装类型和应用场景选择产品，再由 VAYRENZA 与您确认项目所需的尺寸、材料、表面处理、品牌标识及包装方案。',search:'搜索',quote:'索取报价',searchTitle:'产品搜索',placeholder:'按 SKU 或产品名称搜索',close:'关闭',empty:'没有匹配的产品',results:n=>`${n} 个结果`},
    ja:{status:'2026 コアコレクション',nav:['製品','ソリューション','カスタム / OEM','サステナビリティ','VAYRENZAについて','インサイト','お問い合わせ'],eyebrow:'2026 コアコレクション',headline:'58 SKUs.<br>ひとつの統一されたシステム。',intro:'用途に合わせて設計した58のハンガーソリューションを4つの明確なシリーズに体系化。衣類を守り、売場での見え方を高め、用途ごとの調達・選定をよりシンプルにします。',total:'SKU 合計',summary:['VZ-S · スーツ＆シャツ','VZ-T · パンツ＆スカート','VZ-P · プレミアム＆スペシャルティ','VZ-K · キッズ＆ジュニア'],series:['スーツ＆シャツ','パンツ＆スカート','プレミアム＆スペシャルティ','キッズ＆ジュニア'],desc:['シャツ、ニット、ジャケット、テーラードウェア、コートの肩のラインを守り、統一感のある上質なディスプレイを実現します。','パンツやスカートを確実に保持し、衣類を守りながら省スペースで美しい陳列を支えます。','ホテル、ラグジュアリーリテール、カスタムプログラム向けに、見映え、耐久性、ブランド表現を重視した専門ソリューションです。','子ども服に適したやさしい設計で小さな衣類を守り、ベビー・キッズ・ジュニアコレクションを整然と美しく見せます。'],state:'プロフェッショナルな商品プレゼンテーションのために設計',view:'画像を拡大',rule:'バイヤーガイド',ruleTitle:'明確な選択。安心できる調達。',ruleBody:'衣類の種類と用途から製品を選び、その後VAYRENZAと寸法、素材、仕上げ、ブランド表示、包装仕様をご確認いただけます。',search:'検索',quote:'見積もり依頼',searchTitle:'製品検索',placeholder:'SKUまたは製品名で検索',close:'閉じる',empty:'該当する製品がありません',results:n=>`${n} 件`},
    ko:{status:'2026 코어 컬렉션',nav:['제품','솔루션','커스텀 / OEM','지속가능성','VAYRENZA 소개','인사이트','문의'],eyebrow:'2026 코어 컬렉션',headline:'58 SKUs.<br>하나의 일관된 시스템.',intro:'용도에 맞게 설계된 58가지 행거 솔루션을 4개의 명확한 시리즈로 구성하여 의류를 보호하고 진열 품질을 높이며 다양한 용도의 소싱과 선택을 간소화합니다.',total:'SKU 합계',summary:['VZ-S · 수트 & 셔츠','VZ-T · 팬츠 & 스커트','VZ-P · 프리미엄 & 스페셜티','VZ-K · 키즈 & 주니어'],series:['수트 & 셔츠','팬츠 & 스커트','프리미엄 & 스페셜티','키즈 & 주니어'],desc:['셔츠, 니트웨어, 재킷, 테일러링, 코트의 어깨 형태를 보호하고 일관된 프리미엄 진열을 구현합니다.','팬츠와 스커트를 안정적으로 고정하면서 의류 보호와 공간 효율적인 진열을 지원합니다.','호텔, 럭셔리 리테일 및 맞춤 프로그램을 위한 전문 솔루션으로 진열, 내구성, 브랜드 아이덴티티를 강화합니다.','작은 의류를 부드럽게 보호하고 베이비, 키즈, 주니어 컬렉션을 정돈된 상태로 진열할 수 있도록 설계했습니다.'],state:'전문적인 상품 진열을 위해 설계',view:'이미지 확대',rule:'바이어 가이드',ruleTitle:'명확한 선택. 자신 있는 소싱.',ruleBody:'의류 유형과 용도에 따라 제품을 선택한 뒤 VAYRENZA와 필요한 치수, 소재, 마감, 브랜딩 및 포장 사양을 확인할 수 있습니다.',search:'검색',quote:'견적 요청',searchTitle:'제품 검색',placeholder:'SKU 또는 제품명으로 검색',close:'닫기',empty:'일치하는 제품이 없습니다',results:n=>`${n}개 결과`}
  };
  window.VAYRENZA_PRODUCT_I18N=Object.freeze({version:'3.0',supported:['en','es','fr','de','zh-CN','ja','ko'],names,copy});
})();